### ISSUE TITLE
Different errors even with cubemap?

### ISSUE THREAD

**Issue by yaakovyitzchak** [keijiro/KinoFog#10]
B"H
This would seem rather simple but I'm trying to do fog in unity to cut out the distance items, and

Tried using kinofog
but I got these errors (after applying cubemap texture to camera)

[tried this](https://i.stack.imgur.com/1thFR.png)

How can I clip out distant objects such that the clipping isn't so sharp, and the intensity of the fog isn't cutting it out?

**Comment by keijiro** [comment]
I'd recommend starting over from removing and importing the package again, using KinoFog.unitypackage.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by yaakovyitzchak** [comment]
@keijiro i used the built in cubemap instead of mine and it worked, then i copied the settings
