### ISSUE TITLE
It looks broken on My Android Device

### ISSUE THREAD

**Issue by Rapunzel0514** [keijiro/KinoFog#8]
Thanks for share this , it is really awesome!
But I have trouble when I use it on android.
It works good in Editor. Like this:
![default](https://user-images.githubusercontent.com/30684948/39557135-f9d32202-4eb7-11e8-9a0b-09015c7e2ebe.PNG)

But it looks black and white on Android.
![aa](https://user-images.githubusercontent.com/30684948/39557098-b5e0a6e6-4eb7-11e8-8ade-823642780fc9.PNG)
Any idea?

**Comment by keijiro** [comment]
It only works with the deferred rendering path. Does your device support it?

**Comment by Rapunzel0514** [comment]
Thanks for your response.
Sorry,I don't know whether my device is support it.
But I fix this problem now.
I made some changes based on your code.(I hope you don’t mind)
→ https://github.com/Rapunzel0514/FogFadeinSkybox
And it works for me now.
Thanks again.This is really helpful.

**Comment by keijiro** [comment]
Sure. Good to hear that the problem was solved on your side.
