### ISSUE TITLE
using this effect doubles the DC/Batches :(

### ISSUE THREAD

**Issue by alicewithalex** [keijiro/KinoFog#9]
Hello, I am very happy that found this effect, but cant use it on mobile with good perfomance cause it doubles all DC/Batches for me...
![Screenshot_4](https://user-images.githubusercontent.com/25932220/94341326-17e10900-0011-11eb-9198-3e5654aae0e8.png)

**Comment by keijiro** [comment]
Because it uses the depth texture. The additional depth pass doesn't happen for the deferred rendering path, but if you're using the forward rendering path, it can't be avoidable.
